name: 'TypeDoc'
author: 'Zakodium'
description: 'Build documentation using TypeDoc'
inputs:
  entry:
    description: 'Entry point of your API'
    required: true
    default: 'src/index.ts'
  config:
    description: 'Path of the config file (json)'
  pnpm: 
    description: 'Specify if the pnpm package manager has to be used on the script'
    default: 'false'
  name:
    description: 'Name of the package'
runs:
  using: 'node20'
  main: 'index.mjs'
